Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,7 +31,13 @@ jobs:
 
     - name: Get Jenkins crumb
       run: |
-        CRUMB=$(curl -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" | jq -r '.crumb')
+        RESPONSE=$(curl -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json")
+        echo "Response from Jenkins: $RESPONSE"
+        CRUMB=$(echo $RESPONSE | jq -r '.crumb' || echo "")
+        if [ -z "$CRUMB" ]; then
+          echo "Failed to obtain a crumb from Jenkins."
+        exit 1
+        fi
         echo "CRUMB=$CRUMB" >> $GITHUB_ENV
       env:
         JENKINS_URL: ${{ secrets.JENKINS_URL }}
